import { Body, Controller, Get, Param, Post, Put } from '@nestjs/common';
import { UserService } from './user.service';
import { CreateUserDto } from './dto/create-user.dto';
import { UserEntity } from './user.entity';
import { v4 as uuid } from 'uuid';
import { ListUserDto } from './dto/list-user.dto';
import { UpdateUserDto } from './dto/update-user.dto';
@Controller('/users') // 👈 Route path @Controller is a decorator that defines a controller that will handle requests for a specific route path.
export class UserController {
  /*  private userService = new UserService(); */ // 👈 Create an instance of the UserService class

  constructor(private userService: UserService) {} // 👈 Dependency injection in the constructor to inject the UserService instance into the UserController class.

  @Post() // 👈 Route handler @Post is a decorator that defines a route handler for POST requests to the route path defined by the @Controller decorator.
  async createUser(@Body() body: CreateUserDto) {
    // 👈 Route handler method that accepts a CreateUserDto object as the request body.
    // create user
    const userEntity = new UserEntity(); // 👈 Create an instance of the UserEntity class

    userEntity.name = body.name; // 👈 Set the name property of the userEntity object to the name property of the CreateUserDto object
    userEntity.email = body.email; // 👈 Set the email property of the userEntity object to the email property of the CreateUserDto object
    userEntity.password = body.password; // 👈 Set the password property of the userEntity object to the password property of the CreateUserDto object
    userEntity.id = uuid(); // 👈 Set the id property of the userEntity object to a unique id generated by the uuid package

    this.userService.createUser(userEntity);
    return {
      // 👈 return user object;
      user: new ListUserDto(userEntity.id, userEntity.name), // 👈 return a new ListUserDto object with the id and name properties of the userEntity object
      message: 'User created successfully',
    };
  }

  @Get()
  async getUsers() {
    const savedUsers = await this.userService.getUsers(); // 👈 Call the getUsers method of the UserService class and assign the result to the savedUsers variable
    const users = savedUsers.map((user) => {
      // 👈 Map the savedUsers array to a new array of objects with only the id and name properties
      return new ListUserDto(user.id, user.name);
    });
    return users; // 👈 return users array
  }

  @Put('/:id')
  async updateUser(@Body() body: UpdateUserDto, @Param('id') id: string) {
    const updatedUser = await this.userService.updateUser(id, body);

    return {
      user: new ListUserDto(updatedUser.id, updatedUser.name),
      message: 'User updated successfully',
    };
  }
}
