import { Body, Controller, Get, Post } from "@nestjs/common";
import { UserService } from "./user.service";
import { CreateUserDto } from "./dto/create-user.dto";
import { UserEntity } from "./user.entity";
import { v4 as uuid } from "uuid";
@Controller("/users") // 👈 Route path @Controller is a decorator that defines a controller that will handle requests for a specific route path.
export class UserController {
   /*  private userService = new UserService(); */ // 👈 Create an instance of the UserService class

    constructor(private userService: UserService) {} // 👈 Dependency injection in the constructor to inject the UserService instance into the UserController class.

    @Post() // 👈 Route handler @Post is a decorator that defines a route handler for POST requests to the route path defined by the @Controller decorator. 
    async createUser(@Body() body: CreateUserDto) { // 👈 Route handler method that accepts a CreateUserDto object as the request body.
        // create user
        const userEntity = new UserEntity(); // 👈 Create an instance of the UserEntity class

        userEntity.name = body.name; // 👈 Set the name property of the userEntity object to the name property of the CreateUserDto object
        userEntity.email = body.email; // 👈 Set the email property of the userEntity object to the email property of the CreateUserDto object
        userEntity.password = body.password; // 👈 Set the password property of the userEntity object to the password property of the CreateUserDto object
        userEntity.id = uuid(); // 👈 Set the id property of the userEntity object to a unique id generated by the uuid package

        this.userService.createUser(userEntity);
        return { // 👈 return user object;
            id: userEntity.id,
            message: "User created successfully",
        } 
    }

    @Get()
    async getUsers() {
        // get users
        return this.userService.getUsers(); // 👈 Response 
    }

}
